-- Tables Creation.

-- STUDENTS
CREATE TABLE students (
    student_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR2(50),
    last_name      VARCHAR2(50),
    dob            DATE,
    department     VARCHAR2(50),
    enrollment_year NUMBER(4)
);

--DATA

INSERT INTO students (first_name, last_name, dob, department, enrollment_year)
VALUES ('Alice', 'Johnson', DATE '2002-05-12', 'Computer Science', 2020);
INSERT INTO students (first_name, last_name, dob, department, enrollment_year)
VALUES ('Bob', 'Brown', DATE '2001-09-20', 'Mathematics', 2019);
INSERT INTO students (first_name, last_name, dob, department, enrollment_year)
VALUES ('Clara', 'Lee', DATE '2003-02-01', 'Computer Science', 2021);

-- FACULTY
CREATE TABLE faculty (
    faculty_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR2(50),
    last_name      VARCHAR2(50),
    department     VARCHAR2(50)
);

--DATA

INSERT INTO faculty (first_name, last_name, department)
VALUES ('John', 'Doe', 'Computer Science');
INSERT INTO faculty (first_name, last_name, department)
VALUES ('Mary', 'Smith', 'Mathematics');
INSERT INTO faculty (first_name, last_name, department)
VALUES ('Alan', 'Turing', 'Computer Science');

-- COURSES
CREATE TABLE courses (
    course_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name    VARCHAR2(100),
    department     VARCHAR2(50),
    credits        NUMBER(2),
    faculty_id     NUMBER,
    CONSTRAINT fk_faculty FOREIGN KEY (faculty_id)
        REFERENCES faculty(faculty_id)
);

--DATA

INSERT INTO courses (course_name, department, credits, faculty_id)
VALUES ('Database Systems', 'Computer Science', 3, 1);
INSERT INTO courses (course_name, department, credits, faculty_id)
VALUES ('Algorithms', 'Computer Science', 4, 3);
INSERT INTO courses (course_name, department, credits, faculty_id)
VALUES ('Linear Algebra', 'Mathematics', 3, 2);

-- ENROLLMENTS
CREATE TABLE enrollments (
    enrollment_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     NUMBER,
    course_id      NUMBER,
    semester       VARCHAR2(10),
    enrollment_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES students(student_id),
    CONSTRAINT fk_course FOREIGN KEY (course_id) REFERENCES courses(course_id)
);

--DATA

INSERT INTO enrollments (student_id, course_id, semester)
VALUES (1, 1, 'Fall');
INSERT INTO enrollments (student_id, course_id, semester)
VALUES (1, 2, 'Fall');
INSERT INTO enrollments (student_id, course_id, semester)
VALUES (2, 3, 'Spring');
INSERT INTO enrollments (student_id, course_id, semester)
VALUES (3, 1, 'Fall');

-- GRADES
CREATE TABLE grades (
    grade_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id  NUMBER,
    grade_letter   CHAR(2),
    grade_points   NUMBER(3,2),
    CONSTRAINT fk_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id)
);

--DATA

-- GRADES
INSERT INTO grades (enrollment_id, grade_letter, grade_points)
VALUES (1, 'A', 4.0);
INSERT INTO grades (enrollment_id, grade_letter, grade_points)
VALUES (2, 'B', 3.0);
INSERT INTO grades (enrollment_id, grade_letter, grade_points)
VALUES (3, 'A', 4.0);
INSERT INTO grades (enrollment_id, grade_letter, grade_points)
VALUES (4, 'C', 2.0);




--1	List each student’s enrolled courses with faculty name.

SELECT s.first_name || ' ' || s.last_name as student,c.course_name,
f.first_name || ' ' || f.last_name as faculty
FROM students s
JOIN enrollments   e 
ON s.student_id=e.student_id
JOIN courses c
ON  e.course_id=c.course_id
JOIN faculty f
ON c.faculty_id = f.faculty_id;

--2	Calculate average GPA per department.

SELECT s.department, ROUND(AVG(g.grade_points),2) as AVG_grade from grades g
JOIN enrollments e  
ON g.enrollment_id = e.enrollment_id
JOIN students s
ON s.student_id = e.student_id
GROUP BY s.department;

--3	Write a procedure to enroll a student.

CREATE OR REPLACE PROCEDURE enroll(p_student_id NUMBER, p_course_id NUMBER, p_semester VARCHAR2) AS
BEGIN
    INSERT INTO enrollments (student_id, course_id, semester)
    VALUES(p_student_id,p_course_id, p_semester);
EXCEPTION 
    WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('Entry already exist'); 
END;
/
--4	Write a function to calculate GPA for a student.

CREATE OR REPLACE FUNCTION fn_calculate_gpa(p_student_id NUMBER)
RETURN NUMBER AS
v_avg_gpa NUMBER;
BEGIN
    SELECT AVG(g.grade_points) INTO v_avg_gpa 
    FROM enrollments e JOIN  grades g
    ON e.ENROLLMENT_ID = g.ENROLLMENT_ID
    WHERE e.STUDENT_ID = p_student_id;
    RETURN NVL(v_avg_gpa,0);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No data found');
    RETURN 0;
END;
/
--5	Prevent duplicate enrollment for same course & semester.

CREATE OR REPLACE TRIGGER tr_prv_dups
BEFORE INSERT ON enrollments
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM enrollments
    WHERE student_id = :NEW.student_id AND 
    course_id = :NEW.course_id AND 
    semester = :NEW.semester;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001,'Entry Already Exist');
    END IF;
END;
/


--6	Auto-assign grade_points based on grade_letter.

CREATE OR REPLACE TRIGGER tr_auto_grd
BEFORE INSERT OR UPDATE ON grades
FOR EACH ROW
BEGIN
    CASE :NEW.grade_letter
        WHEN 'A' THEN :NEW.grade_points:= 4.0;
        WHEN 'B' THEN :NEW.grade_points:= 3.0;
        WHEN 'C' THEN :NEW.grade_points:= 2.0;
        WHEN 'D' THEN :NEw.grade_points:= 1.0;
        ELSE :NEW.grade_points:=0.0;
    END CASE;
END;
/

INSERT INTO grades (enrollment_id, grade_letter)
VALUES(2,'B');

SELECT * FROM grades;

--7	Display all students and their GPA. 

DECLARE
    CURSOR c is SELECT student_id,first_name, last_name from STUDENTS;
    v_avg_gpa NUMBER:=0;
BEGIN
    FOR i in c LOOP
    v_avg_gpa:=ROUND(fn_calculate_gpa(i.student_id),2);
    DBMS_OUTPUT.PUT_LINE(i.first_name || ' ' || i.last_name || ' has GPA ' ||v_avg_gpa);
    END LOOP;
END;
/
--8	Group enrollment operations in a package. 

CREATE OR REPLACE PACKAGE pkg_enrollment AS
PROCEDURE enroll(p_student NUMBER, p_course NUMBER, p_sem VARCHAR2);
PROCEDURE unenroll(p_enrollment_id NUMBER);
END;
/

CREATE OR REPLACE PACKAGE BODY pkg_enrollment AS
PROCEDURE enroll(p_student NUMBER, p_course NUMBER, p_sem VARCHAR2) AS
BEGIN
    INSERT INTO enrollments (student_id, course_id, semester)
    VALUES(p_student, p_course, p_sem);
    COMMIT;
END;

PROCEDURE unenroll(p_enrollment_id NUMBER) AS
BEGIN
    DELETE FROM grades WHERE enrollment_id = p_enrollment_id;
    DELETE FROM enrollments WHERE enrollment_id = p_enrollment_id;
    COMMIT;
END;
END pkg_enrollment;

--9	Handle “student not found” in GPA function.

CREATE OR REPLACE FUNCTION fn_calculate_gpa_exc(p_student_id NUMBER)
RETURN NUMBER AS
v_avg_gpa NUMBER;
BEGIN
    SELECT AVG(g.grade_points) INTO v_avg_gpa 
    FROM enrollments e JOIN  grades g
    ON e.ENROLLMENT_ID = g.ENROLLMENT_ID
    WHERE e.STUDENT_ID = p_student_id;
    RETURN NVL(v_avg_gpa,0);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20011,'Student not found');
    RETURN 0;
END;
/

--10 Transfer student to another department.

CREATE OR REPLACE PROCEDURE trandfer_dept(p_student_id NUMBER,p_department VARCHAR2) AS
BEGIN
    UPDATE students SET department = p_department
    WHERE student_id = p_student_id;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Student Not Found');
    ROLLBACK;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Transfer failed: ' || SQLERRM);
        ROLLBACK;
        RAISE;
END;
/

--11 Fetch all grade data for analytics.
DECLARE
TYPE t_all_grade IS RECORD (enrollment_id NUMBER,student_id NUMBER,course_id NUMBER,grade_point NUMBER);
TYPE t_all_grade_tab IS TABLE OF t_all_grade;
b_all_grades t_all_grade_tab;
BEGIN
    SELECT e.enrollment_id,e.student_id,e.course_id,g.grade_points
    BULK COLLECT INTO b_all_grades
    FROM enrollments e 
    JOIN grades g 
    ON e.ENROLLMENT_ID = g.ENROLLMENT_ID;
    FOR i in 1..b_all_grades.COUNT LOOP 
        DBMS_OUTPUT.PUT_LINE('ENROLLMENT ID = '||b_all_grades(i).enrollment_id ||',STUDENT ID = '||b_all_grades(i).student_id ||',COURSE ID = '||b_all_grades(i).course_id ||',GRADE = '||b_all_grades(i).grade_point ||'.');
    END LOOP;
END;
/

--12	FORALL	Bulk insert new enrollments	Performance.

DECLARE
    TYPE t_enroll_id IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    v_enroll_id t_enroll_id;
    v_course_id NUMBER:= 3;
    v_sem VARCHAR2(20):= 'Fall';
BEGIN
    v_enroll_id(1):=9;
    v_enroll_id(2):=4;
    FORALL i in INDICES of v_enroll_id
    INSERT INTO enrollments (student_id,course_id,semester)
    VALUES (v_enroll_id(i),v_course_id,v_sem);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT  || ' rows inserted.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM  || ' happened.');
        ROLLBACK;
END;
/


--13 Create view for transcript summary.

CREATE OR REPLACE VIEW view_transcript AS
SELECT s.student_id, s.first_name || ' ' || s.last_name AS name, 
        c.course_name,g.grade_letter,g.grade_points 
        FROM students s JOIN enrollments e 
        ON e.STUDENT_ID = s.STUDENT_ID
        JOIN courses c ON c.course_id = e.COURSE_ID
        LEFT JOIN grades g ON g.ENROLLMENT_ID=e.ENROLLMENT_ID;
        
--14 Create summary of average grade per course.

BEGIN
EXECUTE IMMEDIATE 
'CREATE OR REPLACE MATERIALIZED VIEW m_avg_grd_course BUILD IMMEDIATE REFRESH COMPLETE ON DEMAND AS
SELECT  c.course_id,c.course_name,ROUND(AVG(g.grade_points),2) as avg_grade 
        FROM grades g JOIN enrollments e 
        ON g.ENROLLMENT_ID=e.ENROLLMENT_ID
        JOIN courses c ON c.course_id = e.COURSE_ID
        GROUP BY c.course_id,c.course_name';
EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/


--15 Generate report for any semester.

CREATE OR REPLACE PROCEDURE semester_report(p_semester VARCHAR2) AS 
TYPE refcur IS REF CURSOR;
rc refcur;
v_student_name VARCHAR2(100);
v_course_name VARCHAR2(100);
v_grade_letter VARCHAR2(6);
v_grade_points NUMBER;

BEGIN
        OPEN rc FOR 'SELECT s.first_name || '' '' || s.last_name, c.course_name, g.grade_letter, g.grade_points
                 FROM students s JOIN enrollments e ON s.student_id = e.student_id
                 JOIN courses c ON e.course_id = c.course_id JOIN grades g ON e.enrollment_id = g.enrollment_id
                 WHERE e.semester = :1' USING p_semester;
        LOOP
            FETCH rc INTO v_student_name,v_course_name ,v_grade_letter ,v_grade_points;
            EXIT WHEN rc%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(v_student_name || ' | ' || v_course_name || ' | ' || v_grade_letter || ' | ' || v_grade_points);
        END LOOP;
        CLOSE rc;
END;
/


--16	DBMS_OUTPUT	Print student report. 

DECLARE
    CURSOR c IS SELECT s.student_id, s.first_name || ' ' || s.last_name AS name, 
        co.course_name as course ,g.grade_letter as grade_letter ,g.grade_points as grade_points
        FROM students s JOIN enrollments e 
        ON e.STUDENT_ID = s.STUDENT_ID
        JOIN courses co ON co.course_id = e.COURSE_ID
        LEFT JOIN grades g ON g.ENROLLMENT_ID=e.ENROLLMENT_ID;
BEGIN
    FOR i in c LOOP
        DBMS_OUTPUT.PUT_LINE(i.name || ' ' ||i.course ||  ' ' ||i.grade_letter || ' ' ||i.grade_points );
    END LOOP;
END;
/


--17	Use sequence explicitly for enrollment_id.

CREATE SEQUENCE seq_enrollment START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

--18    Add index on course_id for faster search.

CREATE INDEX idx_enroll_course ON enrollments(course_id);
CREATE INDEX idx_enroll_student ON enrollments(student_id);


--19    Maintain audit trail for grade updates. 

CREATE TABLE audit_grade (
    grade_id NUMBER(10),
    enrollment_id NUMBER(10),
    old_letter CHAR(2),
    new_letter CHAR(2),
    old_points NUMBER(3,2),
    new_points NUMBER(3,2),
    changed_by VARCHAR2 (30) DEFAULT USER,
    changed_date DATE DEFAULT SYSDATE
)

Drop table audit_grade
CREATE OR REPLACE TRIGGER tr_audit_grade
BEFORE UPDATE OF grade_letter, grade_points ON GRADES
FOR EACH ROW
BEGIN
    INSERT INTO audit_grade (grade_id, enrollment_id, old_letter, new_letter, old_points, new_points, changed_by)
    VALUES (:OLD.grade_id, :OLD.enrollment_id, :OLD.grade_letter, :NEW.grade_letter, :OLD.grade_points, :NEW.grade_points, USER);
END trg_grade_audit;
/

--20    JOB Schedule monthly data purge.

CREATE OR REPLACE PROCEDURE pr_clean_audit_table AS
BEGIN
    DELETE FROM audit_grade WHERE changed_date < (SYSDATE - INTERVAL '2' YEAR);
END;
/



BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name => 'audit_clean',
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN pr_clean_audit_table; END;',
        start_date => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MONTHLY;BYMONTHDAY=13',
        enabled => TRUE

    );
END;
/